# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0db9d7ec3fb287956c255501f6bd4d95b0ea5b831ef2e959fe7739c846004d1f0b69fca2261e87ff2ea06833b778296d5d2cad235f3ccec0ef9ffc72ba8e21cb

test:
  secret_key_base: c0290544c7a9199d0568e719f43aabe3377cfabf75810ef58e0d718343e545daafa964ea9ef67d35b35a9611717cca33c944fdde47e652c99c9de12a1270203f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
